version: 0.0 
os: linux 
files: 
 - source:  s3://flashbucket1/kudos/Flash_Job-1847672421979155779.zip
   destination: /home/tomcat/apache-tomcat-8.0.36/webapps/kudos.war
hooks: 
   ApplicationStop: 
     - location: scripts/stop_application 
       timeout: 300 
   BeforeInstall: 
     - location: scripts/install_dependencies 
       timeout: 300 
   ApplicationStart: 
     - location: scripts/start_application 
       timeout: 300
