version: 0.0 
os: linux 
files: 
 - source:  
   destination: /tmp/ 
hooks: 
   ApplicationStop: 
     - location: scripts/stop_application 
       timeout: 300 
   BeforeInstall: 
     - location: scripts/install_dependencies 
       timeout: 300 
   ApplicationStart: 
     - location: scripts/start_application 
       timeout: 300
